### ISSUE TITLE
The 0.2 dex floor on errors- where'd it come from? -Ho

### ISSUE THREAD

**Issue by Alex162** [Alex162/Mg-K-Hollyweirdos#12]
My understanding is that this floor was basically just something you (andy) implemented to account for crappiness in the LAMOST spectra or model that the abundance codes don't take into account when doing their uncertainties?

**Comment by andycasey** [comment]
Yes: we adopt a conservative lower limit of 0.2 dex because LAMOST data are crappy and we are trying to measure an abundance from  flux differences, where some of those flux differences may not just be from the element we are trying to measure! So there is some systematic floor here,  which we conservatively estimate as 0.2 dex.

It's OK to say somethign to that effect in the paper.

**Comment by andycasey** [comment]
Have you already added a sentence to this effect?
